AllCops:
  DisabledByDefault: true

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: 'hash_rockets'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/ConstantName:
  Enabled: false
