AllCops:
  DisabledByDefault: true

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: 'ruby19'

Style/FrozenStringLiteralComment:
  EnforcedStyle: always_true

Style/StringLiterals:
  EnforcedStyle: single_quotes
