inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: 'hash_rockets'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/CollectionCompact:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/CaseIndentation:
  EnforcedStyle: end
